name: 1获取最新脚本
on:
  schedule:
    - cron: '5 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-zero205-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.sync-repo }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync zero205-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/zero205/JD_tencent_scf.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: env.PAT
